import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export const Contact = () => {
    return (
        <div className="layout">
            <Head>
                <title>Contact Us</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="wrap">
                <section className="main head_bg">
                    <div className="top_heading">
                        <h1>Contact Us</h1>
                        <p>
                            <Link href="/"><a className="text-decoration-none">Home</a></Link> <i className="fas fa-chevron-right"></i> <span> Contact Us</span>
                        </p>
                    </div>
                </section>
                <div className="container">
                    <section className="contact">
                        <div className="d-md-flex">
                            <div className="col-md-6">
                                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13691.48038340012!2d75.843105!3d30.918255!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x9eaac79c3166e275!2sAbstain%20Solutions!5e0!3m2!1sen!2sin!4v1629118802615!5m2!1sen!2sin" width="100%" height="620" allowFullScreen="" loading="lazy"></iframe>
                            </div>
                            <div className="col-md-6">
                                <h2 className="text-center">Contact Us</h2>
                                <hr className="line" />
                                <from className="contact_form">
                                    <div className="form-row">
                                        <div className="form-group col-md-6">
                                            <label htmlFor="fname">First Name</label>
                                            <input type="text" className="form-control shadow-none rounded-0" id="fname" placeholder="First Name" />
                                        </div>
                                        <div className="form-group col-md-6">
                                            <label htmlFor="lname">Last Name</label>
                                            <input type="text" className="form-control shadow-none rounded-0" id="lname" placeholder="Last Name" />
                                        </div>
                                    </div>
                                    <div className="form-row">
                                        <div className="form-group col-md-6">
                                            <label htmlFor="email">Email Address</label>
                                            <input type="email" className="form-control shadow-none rounded-0" id="email" placeholder="Email Address" />
                                        </div>
                                        <div className="form-group col-md-6">
                                            <label htmlFor="phone">Phone</label>
                                            <input type="number" className="form-control shadow-none rounded-0" id="phone" placeholder="Phone number" />
                                        </div>
                                    </div>
                                    <div className="form-group">
                                        <label htmlFor="Subject">Subject</label>
                                        <input type="test" className="form-control shadow-none rounded-0" id="Subject" placeholder="Subject" />
                                    </div>
                                    <div className="form-group">
                                        <label htmlFor="message">Message</label>
                                        <textarea className="form-control shadow-none rounded-0" id="message" rows="7"></textarea>
                                    </div>
                                    <button type="button" className="btn readmore_btn w-100 shadow-none">Submit</button>
                                </from>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    )
}

export default Contact