import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export const Services = () => {
    return (
        <div className="layout">
        <Head>
            <title>Services</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
            <div className="wrap">
                <section className="main head_bg">
                    <div className="top_heading">
                        <h1>Services</h1>
                        <p>
                            <Link href="/"><a className="text-decoration-none">Home</a></Link> <i className="fas fa-chevron-right"></i> <span> Services</span>
                        </p>
                    </div>
                </section>
                <div className="container">
                </div>
            </div>
        </div>
    )
}

export default Services