import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import service1 from '../public/assets/images/srv-1.jpg'

export const Services = () => {
    return (
        <div className="layout">
            <Head>
                <title>Services</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="wrap">
                <section className="main head_bg">
                    <div className="top_heading">
                        <h1>Services</h1>
                        <p>
                            <Link href="/"><a className="text-decoration-none">Home</a></Link> <i className="fas fa-chevron-right"></i> <span> Services</span>
                        </p>
                    </div>
                </section>
                <section className="our_services">
                    <div className="container">
                        <div className="d-md-flex">
                            <div className="col-md-4">
                                <div className="services_heading">
                                    <h3>What <span>Max Movers</span> Do</h3>
                                    <p>Movin on up to the east side. We finally got a piece of the pie. Fleeing from s the Cylon tyrany the last Battlestar Galactica  leads a rainothin wrong with that.</p>
                                    <p>air of gold theone in curls. As long as we live its you and me baby. T There ain&apos;t nothin wrong with that. It&apos;s a beautiful day in this neighborhood.</p>
                                </div>
                            </div>
                            <div className="col-md-8">
                                <div className="d-md-flex">
                                    <div className="col-md-4 service_box">
                                        <Image src={service1} className="img-fluid" />
                                        <div className="service">
                                            <span>AUTO TRANSPORT</span>
                                            <p>Rong with that. All of them had hair of gold like their mother the way of san taht can be easily.</p>
                                            <Link href="#">
                                                <a className="text-decoration-none">Read More</a>
                                            </Link>
                                        </div>
                                    </div>
                                    <div className="col-md-4 service_box">
                                        <Image src={service1} className="img-fluid" />
                                        <div className="service">
                                            <span>MOVING & STORAGE</span>
                                            <p>Rong with that. All of them had hair of gold like their mother the way of san taht can be easily.</p>
                                            <Link href="#">
                                                <a className="text-decoration-none">Read More</a>
                                            </Link>
                                        </div>
                                    </div>
                                    <div className="col-md-4 service_box">
                                        <Image src={service1} className="img-fluid" />
                                        <div className="service">
                                            <span>PACKING & UNPACKING</span>
                                            <p>Rong with that. All of them had hair of gold like their mother the way of san taht can be easily.</p>
                                            <Link href="#">
                                                <a className="text-decoration-none">Read More</a>
                                            </Link>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    )
}

export default Services