import Head from 'next/head'
import Link from 'next/link'

export const Signup = () => {
    return (
        <div className="layout">
            <Head>
                <title>Signup</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="wrap">
                <section className="login">
                    <div className="container">
                        <div className="col-6 mx-auto">
                            <div className="position-relative">
                                <div className="login_card">
                                    <h3>Sign up</h3>
                                    <form>
                                        <div className="form-row">
                                            <div className="form-group login_group col-md-6">
                                                <input type="text" className="form-control shadow-none rounded-0" placeholder="First Name" />
                                            </div>
                                            <div className="form-group login_group col-md-6">
                                                <input type="text" className="form-control shadow-none rounded-0" placeholder="Last Name" />
                                            </div>
                                        </div>
                                        <div className="form-row">
                                            <div className="form-group login_group col-md-6">
                                                <input type="number" className="form-control shadow-none rounded-0" placeholder="Phone Number" />
                                            </div>
                                            <div className="form-group login_group col-md-6">
                                                <input type="date" className="form-control shadow-none rounded-0" placeholder="" />
                                            </div>
                                        </div>
                                        <div className="form-group login_group">
                                            <input type="email" className="form-control shadow-none rounded-0" placeholder="Email Address" />
                                        </div>
                                        <div className="form-group login_group">
                                            <input type="password" className="form-control shadow-none rounded-0" placeholder="Password" />
                                        </div>
                                        <Link href="#!">
                                            <a className="shadow-none rounded-0 btn login_btn w-100">Sign Up</a>
                                        </Link>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>
                </section>

            </div>
        </div>
    )
}

export default Signup